In [108]:
import doctest
import numpy as np

### Masyvo kūrimo metodai

In [66]:
np.zeros_like(arr)

array([[0, 0, 0, 0],
       [0, 0, 0, 0],
       [0, 0, 0, 0]])

In [69]:
np.zeros((3, 4), dtype=int)

array([[0, 0, 0, 0],
       [0, 0, 0, 0],
       [0, 0, 0, 0]])

In [70]:
np.ones((3, 4), dtype=bool)

array([[ True,  True,  True,  True],
       [ True,  True,  True,  True],
       [ True,  True,  True,  True]])

In [71]:
np.empty((3, 4), dtype=float) #rezervuojamos atsitiktinės atminties ląstelės float tipo duomenims

array([[1.22751595e-311, 2.86558075e-322, 0.00000000e+000,
        0.00000000e+000],
       [1.11260619e-306, 2.42336543e-057, 4.22087287e-090,
        1.04049517e-042],
       [8.26240115e-072, 1.32368490e-071, 6.48224659e+170,
        5.82471487e+257]])

In [75]:
np.full((3, 4), fill_value=2, dtype=np.uint8)

array([[2, 2, 2, 2],
       [2, 2, 2, 2],
       [2, 2, 2, 2]], dtype=uint8)

In [81]:
np.eye(5, dtype=int)

array([[1, 0, 0, 0, 0],
       [0, 1, 0, 0, 0],
       [0, 0, 1, 0, 0],
       [0, 0, 0, 1, 0],
       [0, 0, 0, 0, 1]])

In [82]:
np.repeat(np.arange(5), [9, 3, 0, 7, 1])

array([0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 1, 1, 3, 3, 3, 3, 3, 3, 3, 4])

In [84]:
np.tile(np.arange(3), 4)

array([0, 1, 2, 0, 1, 2, 0, 1, 2, 0, 1, 2])

In [83]:
np.tile(np.arange(5), (3, 4))

array([[0, 1, 2, 3, 4, 0, 1, 2, 3, 4, 0, 1, 2, 3, 4, 0, 1, 2, 3, 4],
       [0, 1, 2, 3, 4, 0, 1, 2, 3, 4, 0, 1, 2, 3, 4, 0, 1, 2, 3, 4],
       [0, 1, 2, 3, 4, 0, 1, 2, 3, 4, 0, 1, 2, 3, 4, 0, 1, 2, 3, 4]])

Šįsyk dirbsime su masyvu, sudarytu iš atstiktinai sugeneruotų reikšmių:

In [3]:
arr = np.random.randint(20, size=(3, 4))
arr

array([[16, 11,  5, 11],
       [17, 12, 14, 15],
       [10, 13, 15, 18]])

### Masyvo metaduomenys

Masyvas turi dvi ašis, kurių ilgiai yra tokie:

In [4]:
arr.shape

(3, 4)

Masyvo dydis:

In [5]:
arr.size

12

Masyvo duomenų tipas:

In [6]:
arr.dtype

dtype('int32')

Masyvo duomens dydis baitais:

In [7]:
arr.itemsize

4

Masyvo duomenims saugoti numatytos vietos dydis baitais (neįskaitant metaduomenų):

In [8]:
arr.nbytes

48

Kai kurie metaduomenys apie masyvą yra paslėpti privačiame atribute:

In [103]:
arr.__array_interface__

{'data': (2484539640272, False),
 'strides': None,
 'descr': [('', '<i4')],
 'typestr': '<i4',
 'shape': (3, 4),
 'version': 3}

In [76]:
np.iinfo(np.uint8) #Greitas būdas pasižiūrėti duomenų ribas

iinfo(min=0, max=255, dtype=uint8)

In [77]:
np.array([255,254,253], dtype=np.uint8) + 2 #Kas įvyksta, kai peržengiam ribas

array([  1,   0, 255], dtype=uint8)

### Dinaminės operacijos
Dinaminėmis operacijomis laikomos tokios operacijos, kurios negrąžinamai pakeičia pradinį masyvą.

**Eilutės keitimas:**

In [9]:
arr[0] = np.arange(2, 6)
arr

array([[ 2,  3,  4,  5],
       [17, 12, 14, 15],
       [10, 13, 15, 18]])

**Bloko keitimas:**

In [10]:
arr[1:, 1:3] = -1
arr

array([[ 2,  3,  4,  5],
       [17, -1, -1, 15],
       [10, -1, -1, 18]])

### Indeksavimo rūšys

**Priėjimas prie elemento:**

In [11]:
arr[0,2], arr[0][2]

(4, 4)

**Indeksavimas pagal pirmą ašį**:

In [12]:
my_list = [0, 2]
print(arr[my_list])
print(arr[my_list, :])

[[ 2  3  4  5]
 [10 -1 -1 18]]
[[ 2  3  4  5]
 [10 -1 -1 18]]


**Indeksavimas pagal abi ašis**:

In [13]:
print(arr[[0, 2], ::2])

[[ 2  4]
 [10 -1]]


**Indeksavimas pagal antrą ašį**:

In [14]:
print(arr[:, ::2])

[[ 2  4]
 [17 -1]
 [10 -1]]


### Indeksų praleidimo slice'suose prasmė
Įsitikinsime, kad  `numpy` masyvų ir `list` indeksacija yra paremta `slice` tipo objektų naudojimu:

In [15]:
a = [7,8,9,4,5,6,1,2,3]
a[::2], a[None:None:2], a[slice(None,None,2)]

([7, 9, 5, 1, 3], [7, 9, 5, 1, 3], [7, 9, 5, 1, 3])

In [16]:
a[2:], a[2:None:None], a[slice(2, None, None)]

([9, 4, 5, 6, 1, 2, 3], [9, 4, 5, 6, 1, 2, 3], [9, 4, 5, 6, 1, 2, 3])

Taip pat panagrinėsime, kaip tokia indeksacija veikia `numpy` masyvuose, kai indeksuojamos abi ašys (`list` tipo objektai palaiko tik pirmos ašies indeksaciją):

In [17]:
arr

array([[ 2,  3,  4,  5],
       [17, -1, -1, 15],
       [10, -1, -1, 18]])

In [18]:
s1, s2 = slice(1,4,2), slice(1,3,2) # 1
l1, l2 = [1, 3], [1]

In [19]:
arr[s1, s2], arr[1:4:2, 1:3:2] #tokia pati indeksacija, paima tik pirmą eilutę ir pirmą stulpelį

(array([[-1]]), array([[-1]]))

In [20]:
arr[l1, s2], arr[[1, 3], 1:3:2] #tokia pati indeksacija, tačiau išmeta IndexError, nes neranda trečios eilutės

IndexError: index 3 is out of bounds for axis 0 with size 3

In [21]:
arr[s1, l2], arr[1:4:2, [1]] #tokia pati indeksacija, paima pirmą eilutę ir pirmą stulpelį

(array([[-1]]), array([[-1]]))

### Advanced indexing

In [22]:
arr

array([[ 2,  3,  4,  5],
       [17, -1, -1, 15],
       [10, -1, -1, 18]])

**Neapsigauti: kai visų ašių indeksai yra `list` tipo, tai indeksacija tampa Advanced**

In [23]:
l1, l2 = [0, 2], [0, 2]
arr[l1, l2]

array([ 2, -1])

**Norint, kad būtų taip, kaip darėme anksčiau:**

In [24]:
arr[np.ix_(l1, l2)]

array([[ 2,  4],
       [10, -1]])

### Boolean indexing
`numpy` masyvai palaiko ne tik `slice` ir `list` tipo objektų naudojimą indeksavime, tačiau taip pat leidžia naudoti ir `bool` tipo indeksus:

In [25]:
my_list = [True, False, True]
print(arr[my_list])
print(arr[[0, 2]]) #turi gautis tas pats

[[ 2  3  4  5]
 [10 -1 -1 18]]
[[ 2  3  4  5]
 [10 -1 -1 18]]


## Antra dalis

**Masyvo formos keitimas.** Keičiant formą suformuojamas naujo masyvo vaizdas, tačiau kopija nesukuriama ir dirbama su tuo pačiu:

In [51]:
arr

array([[ 2,  3,  4,  5],
       [17, -1, -1, 15],
       [10, -1, -1, 18]])

In [52]:
arr.shape

(3, 4)

In [53]:
x = arr.reshape(3, 2, 2)
x

array([[[ 2,  3],
        [ 4,  5]],

       [[17, -1],
        [-1, 15]],

       [[10, -1],
        [-1, 18]]])

**Masyvo plokštinimas**. `np.ravel` ir `np.flatten` metodai paverčia masyvą plokščiu ir grąžina tą patį rezultatą. Tačiau `np.ravel()` nesukuria jo kopijos, o `np.flatten()` sukuria. Todėl narių keitimas `np.ravel()` outpute yra dinaminis procesas, o `np.flatten()` atveju - nėra.

In [54]:
x.ravel(), np.ravel(x)

(array([ 2,  3,  4,  5, 17, -1, -1, 15, 10, -1, -1, 18]),
 array([ 2,  3,  4,  5, 17, -1, -1, 15, 10, -1, -1, 18]))

In [55]:
x.flatten(), #np.flatten(x) is not supported

(array([ 2,  3,  4,  5, 17, -1, -1, 15, 10, -1, -1, 18]),)

In [60]:
y1, y2 = x.ravel(), x.flatten()
y1[0] = 100
y2[0] = 200
y1, y2

(array([100,   3,   4,   5,  17,  -1,  -1,  15,  10,  -1,  -1,  18]),
 array([200,   3,   4,   5,  17,  -1,  -1,  15,  10,  -1,  -1,  18]))

In [61]:
x

array([[[100,   3],
        [  4,   5]],

       [[ 17,  -1],
        [ -1,  15]],

       [[ 10,  -1],
        [ -1,  18]]])

In [62]:
arr

array([[100,   3,   4,   5],
       [ 17,  -1,  -1,  15],
       [ 10,  -1,  -1,  18]])

Ups, `x` ir `arr` masyvų pirmi nariai pasikeitė. O anksčiau buvę nariai niekur nesaugomi, tad juos praradome! `y1 = x.ravel()` ir `x = arr.reshape(3, 2, 2)` metodai nesukūrė masyvų kopijų, todėl masyvų `x, y1, arr` nariai yra saugomi tose pačiose atminties ląstelėse. Pirmo nario pakeitimas pirmame masyve pakeitė ir likusių masyvų pirmus narius.

**Perėjimai tarp skirtingų indeksacijų.** Jau susipažinome su paprasta, Boolean ir Fancy indeksacija. Dabar pažiūrėkime, kaip galima atkurti indeksus arba pereiti iš vienos indeksacijos į kitą.

In [85]:
arr == -1

array([[False, False, False, False],
       [False,  True,  True, False],
       [False,  True,  True, False]])

In [87]:
np.where(arr == -1) #randa Fancy indeksus narių, lygių -1

(array([1, 1, 2, 2], dtype=int64), array([1, 2, 1, 2], dtype=int64))

In [89]:
np.nonzero(arr == -1) #tas pats

(array([1, 1, 2, 2], dtype=int64), array([1, 2, 1, 2], dtype=int64))

In [95]:
flat_arr = arr.ravel() == -1
flat_arr #palyginimas su -1

array([False, False, False, False, False,  True,  True, False, False,
        True,  True, False])

In [96]:
np.flatnonzero(flat_arr) #randa indeksus narių, lygių -1, išplokštintame masyve

array([ 5,  6,  9, 10], dtype=int64)

In [99]:
arr == -1

array([[False, False, False, False],
       [False,  True,  True, False],
       [False,  True,  True, False]])

In [92]:
np.flatnonzero(arr == -1) #taikant metodą masyvo išplokštinimas nėra būtinas

array([ 5,  6,  9, 10], dtype=int64)

In [98]:
np.divmod([ 5,  6,  9, 10], 4) #triukas, su kuriuo galima paversti išplokštinto masyvo indeksus į fancy indeksus

(array([1, 1, 2, 2], dtype=int32), array([1, 2, 1, 2], dtype=int32))

## Trečia dalis
Prisimename, kaip valdyti kodą, kad juo galėtų naudotis kiti žmonės, kad jis būtų suprantamas ir gerai dokumentuotas. Tuo tikslu pasižiūrėkime bent vieną geros dokumentacijos pavyzdį:

In [127]:
help(np.packbits)

Help on function packbits in module numpy:

packbits(...)
    packbits(a, axis=None, bitorder='big')
    
    Packs the elements of a binary-valued array into bits in a uint8 array.
    
    The result is padded to full bytes by inserting zero bits at the end.
    
    Parameters
    ----------
    a : array_like
        An array of integers or booleans whose elements should be packed to
        bits.
    axis : int, optional
        The dimension over which bit-packing is done.
        ``None`` implies packing the flattened array.
    bitorder : {'big', 'little'}, optional
        The order of the input bits. 'big' will mimic bin(val),
        ``[0, 0, 0, 0, 0, 0, 1, 1] => 3 = 0b00000011``, 'little' will
        reverse the order so ``[1, 1, 0, 0, 0, 0, 0, 0] => 3``.
        Defaults to 'big'.
    
        .. versionadded:: 1.17.0
    
    Returns
    -------
    packed : ndarray
        Array of type uint8 whose elements represent bits corresponding to the
        logical (0 or nonze

**Dokumentacijos kūrimas**

Pasižiūrėkime, kaip atrodo bet kurio mūsų paties aprašyto Python metodo dokumentacija:

In [100]:
def func(x,y):
    return x+y

help(func)

Help on function func in module __main__:

func(x, y)



Pagal `numpy` pavyzdį galime patys lengvai pasirašyti tvarkingą dokumentaciją:

In [101]:
def func(x,y):
    '''Adds two numbers.
    
    Parameters
    ----------
        a, b : scalars
            Two integers which should be added.
        
    Returns
    -------
        out : scalar
            The sum of a and b.
            
    Examples
    --------
    >>> func(1, 3)
    4
    >>> func(-1, 1.5)
    0.5
    '''
    return x+y

help(func)

Help on function func in module __main__:

func(x, y)
    Adds two numbers.
    
    Parameters
    ----------
        a, b : scalars
            Two integers which should be added.
        
    Returns
    -------
        out : scalar
            The sum of a and b.
            
    Examples
    --------
    >>> func(1, 3)
    4
    >>> func(-1, 1.5)
    0.5



**Testų paleidimas**

Dokumentacinėje eilutėje po simbolių `>>>` einančios komandos nėra vien paprasti komandų naudojimo pavyzdžiai skaitytojui. Jos skirtos automatiškai patikrinti, ar naudojamo kodo elgsena yra tokia pati, kokios tikimasi.

In [107]:
if __name__ == '__main__':
    doctest.testmod(verbose=True)

Trying:
    func(1, 3)
Expecting:
    4
ok
Trying:
    func(-1, 1.5)
Expecting:
    0.5
ok
1 items had no tests:
    __main__
1 items passed all tests:
   2 tests in __main__.func
2 tests in 2 items.
2 passed and 0 failed.
Test passed.


Visi testai praėjo! Testų kūrimas koduose - svarbus procesas siekiant užtikrinti geresnį kodo valdymą ir prieinamumą kitiems vartotojams.

**Paketų instaliavimas per Anaconda Prompt**. Pabandykime užkrauti biblioteką:

In [ ]:
import numpy_indexed as npi

Komanda turėtų neveikti, nes tokios bibliotekos nesame susiinstaliavę. Norint suinstaliuoti, išjungiame visus aktyvius notebookus, tada vidinį serverį ir parašome Anaconda terminale komandą `pip install numpy_indexed`. Po instaliacijos vėl pasijungus serverį (įrašius `jupyter notebook` Anaconda terminale) turėtų viskas veikti.

In [10]:
import numpy as np
import numpy_indexed as npi

class Polynomial:
    '''polynomial instance takes pows and coeffs
    >>> type(Polynomial(np.array([0,1]), np.array([1,1])))
    <class '__main__.Polynomial'>'''
    def __init__(self, pows=None, coeffs=None):
        self.pows = pows
        self.coeffs = coeffs

    @staticmethod
    def cartessian_product(*arrays):
        """returns cartessian product of several arrays
        >>> Polynomial().cartessian_product(np.arange(2), np.arange(3)).tolist()
        [[0, 0], [1, 0], [0, 1], [1, 1], [0, 2], [1, 2]]
        """
        return np.stack(np.meshgrid(*arrays), axis=-1).reshape(-1, len(arrays))

    def __mul__(self, other):
        """ returns product of two polynomials
        >>> P = Polynomial(np.array([0,1]), np.array([1,1])) * Polynomial(np.array([0,1,2]), np.array([1,1,1]))
        >>> print(P.pows)
        [0 1 2 3]
        >>> print(P.coeffs)
        [1 2 2 1]
        """
        cells = self.cartessian_product(self.pows, other.pows) # finding pairs of powers
        powers = np.sum(cells, axis=1) # summation of each pair of powers
        coeffs = self.coeffs[cells[:, 0]] * other.coeffs[cells[:, 1]] # multiplication of corresponding coeffs
        terms = np.column_stack([coeffs, powers]) # result as terms (coeff and power in each row)
        return Polynomial(*npi.group_by(terms[:, 1]).sum(terms[:,0])) # reducing similar terms

    def __eq__(self, other):
        """Implementation of equality
        >>> isinstance(Polynomial(np.array([7]), np.array([8])), Polynomial)
        True
        >>> Polynomial(np.array([7]), np.array([8])) == Polynomial(np.array([7]), np.array([8]))
        True
        """
        if isinstance(other, Polynomial):
            pow_equality = np.sort(self.pows) == np.sort(other.pows)
            coeffs_equality = np.sort(self.coeffs) == np.sort(other.coeffs)
            pow_allequal = np.all(pow_equality)
            coeffs_allequal = np.all(coeffs_equality)
            return pow_allequal and coeffs_allequal
        return False

**Klasės `Polynomial` metodai**

Visus klasės metodus galime peržiūrėti naudodami komandą `[func for func in dir(Polynomial) if callable(getattr(Polynomial, func))]`:

In [4]:
print([func for func in dir(Polynomial) if callable(getattr(Polynomial, func))])

['__class__', '__delattr__', '__dir__', '__eq__', '__format__', '__ge__', '__getattribute__', '__gt__', '__init__', '__init_subclass__', '__le__', '__lt__', '__mul__', '__ne__', '__new__', '__reduce__', '__reduce_ex__', '__repr__', '__setattr__', '__sizeof__', '__str__', '__subclasshook__', 'cartessian_product']


Metodai `__init__`, `__mul__`, `__eq__` ir `cartessian_product` buvo sukurti rankomis, o visus likusius metodus Python sukūrė automatiškai.

* `__init__` metodas atsakingas už klasės Polynomial objekto sukūrimą
* `__mul__` apibrėžia daugybos operatorių `*` tarp dviejų Polynomial. Du daugianariai yra dauginami pagal tokias pačias taisykles, kaip mokinomės mokykloje.
* `__eq__` apibrėžia dviejų daugianarių palyginimą naudojanti simbolį `==`. Du daugianariai laikomi lygiais, jeigu sutampa jų koeficientai ir laipsniai.
* `cartessian_product` yra statinis klasės Polynomial metodas. Tokie metodai nenaudoja kreipinio į patį objektą. Šis metodas grąžina visas kombinatorines kelių aibių kombinacijas, kai imamas lygiai vienas skaičius iš kiekvienos aibės. Norint tą padaryti nebūtina naudoti jokio daugianario.

Daugybos `__mul__` apibrėžimas remiasi `cartessian_product` apibrėžimu.

**Klasės `Polynomial` atributai**

In [5]:
p = Polynomial()
p.pows, p.coeffs #by default, jie priskiriami None reikšmėms

(None, None)

Python priimta, kad kviečiant bet kurią klasę, ji iš pradžių kreipasi į `__init__` metodą, jei tokį randa. Šiame metode yra priskiriami atributai, kurie bus vartojami vėliau pagal poreikį.

In [25]:
P = Polynomial([0, 1, 2], [1, 2, 1]) #Polynomial kreipiasi į __init__ metodą, kuris priskiria pows ir coeffs atributus
P.pows, P.coeffs #Pasižiūrim šių atributų reikšmes

(array([0, 1]), array([1, 1]))

Įprastai kurti atributus, kuriems nėra peržiūros metodų, nėra gera programavimo praktika. Šiuo atveju metodus galėjome sukurti taip:

In [16]:
class PolynomialRefactor:
    '''polynomial instance takes pows and coeffs
    >>> type(PolynomialRefactor(np.array([0,1]), np.array([1,1])))
    <class '__main__.PolynomialRefactor'>'''
    def __init__(self, pows=None, coeffs=None):
        self._pows = pows
        self._coeffs = coeffs
    
    def get_pows(self):
        '''return powers of polynomial
        >>> PolynomialRefactor(np.array([0,1]), np.array([1,1])).get_pows()
        array([0, 1])'''
        return self._pows
    
    def get_coeffs(self):
        '''return coeffs of polynomial
        >>> PolynomialRefactor(np.array([0,1]), np.array([1,1])).get_coeffs()
        array([1, 1])'''
        return self._coeffs

### Spręstos užduotys
* [Tomučio užduotėlės](https://klevas.mif.vu.lt/~tomukas/uzduotys/pitonas_2.html) nuo 1 iki 4.
* Codesignal užduotis (masyvo reikšmių, nelygių -1, išrikiavimas didėjimo tvarka)
* Sukurti indeksaciją, kuri suplokština masyvą (duotas masyvas, reikia sudaryti Fancy indeksus, kurie perrenka visus to masyvo narius)

### Užduotys

* Pasinagrinėti `numpy` metodus, kuriuos apsimoka taikyti braižant funkcijų grafikus. Žr. [matematikos pamokos aprašymą](https://github.com/loijord/mokslas_2021/blob/main/Matematika/turinys.ipynb), skyrelį Programavimo užduotėlė Mantui
* Toliau tęsti su [Tomučio užduotėlėmis](https://klevas.mif.vu.lt/~tomukas/uzduotys/pitonas_2.html) nuo 5 iki 8. Jei yra poreikis, pasikartoti, kaip daryti 1 - 4.
* Sukurti bent vieną metodą su dokumentacine eilute, paleisti testus naudojant `doctest.testmod(verbose=True)` komandą
* Sukurti klasę su bent dviem metodais, iš kurių vienas yra `__init__`
* Pridėti šiems metodams dokumentacines eilutes ir paleisti testus

### Svarbu!

Kiekvienai atskirai temai reikėtų stengtis susikurti atskirą `nootebok`ą, nedaryti visko viename faile.

In [17]:
import doctest
if __name__ == '__main__':
    doctest.testmod(verbose=True)

Trying:
    type(Polynomial(np.array([0,1]), np.array([1,1])))
Expecting:
    <class '__main__.Polynomial'>
ok
Trying:
    isinstance(Polynomial(np.array([7]), np.array([8])), Polynomial)
Expecting:
    True
ok
Trying:
    Polynomial(np.array([7]), np.array([8])) == Polynomial(np.array([7]), np.array([8]))
Expecting:
    True
ok
Trying:
    P = Polynomial(np.array([0,1]), np.array([1,1])) * Polynomial(np.array([0,1,2]), np.array([1,1,1]))
Expecting nothing
ok
Trying:
    print(P.pows)
Expecting:
    [0 1 2 3]
ok
Trying:
    print(P.coeffs)
Expecting:
    [1 2 2 1]
ok
Trying:
    Polynomial().cartessian_product(np.arange(2), np.arange(3)).tolist()
Expecting:
    [[0, 0], [1, 0], [0, 1], [1, 1], [0, 2], [1, 2]]
ok
Trying:
    type(PolynomialRefactor(np.array([0,1]), np.array([1,1])))
Expecting:
    <class '__main__.PolynomialRefactor'>
ok
Trying:
    PolynomialRefactor(np.array([0,1]), np.array([1,1])).get_coeffs()
Expecting:
    array([1, 1])
ok
Trying:
    PolynomialRefactor(np.array([