# Advanced and Boolean indexing

In [2]:
import numpy as np
arr = np.random.randint(0, 20, size=(3, 4))
arr

array([[ 2,  5, 18,  0],
       [ 5,  3, 18, 14],
       [ 8,  4,  4,  6]])

### Advanced indexing

In [3]:
arr

array([[ 2,  5, 18,  0],
       [ 5,  3, 18, 14],
       [ 8,  4,  4,  6]])

**Neapsigauti: kai indeksacijoje du `list` tipo objektai, tai indeksacija tampa Advanced**

Čia masyvas `l1` nurodys, iš kurių eilučių yra imami nariai, o `l2` - atitinkamus stulpelius.

In [4]:
l1, l2 = [0, 2], [0, 2]
arr[l1, l2]

array([2, 4])

Galima pasirinkti tuos pačius narius ir pakartortinai:

In [5]:
arr[[2, 1, 2], [2, 3, 2]]

array([ 4, 14,  4])

Norint, kad būtų atrenkamas visas tam tikrų eilučių ir stulpelių turinys:

In [6]:
arr[np.ix_(l1, l2)]

array([[ 2, 18],
       [ 8,  4]])

arba naudojant Basic indexing:

In [7]:
arr[0:3:2, 0:3:2]

array([[ 2, 18],
       [ 8,  4]])

### Boolean indexing
`numpy` masyvai palaiko ne tik `slice` ir `list` tipo objektų naudojimą indeksavime, tačiau taip pat leidžia naudoti ir `bool` tipo indeksus:

In [8]:
bool_idx = np.array([True, False, True])
int_idx = np.array([0, 2])
bool_idx.dtype, int_idx.dtype

(dtype('bool'), dtype('int64'))

In [9]:
print(arr[bool_idx])
print(arr[int_idx]) #turi gautis tas pats

[[ 2  5 18  0]
 [ 8  4  4  6]]
[[ 2  5 18  0]
 [ 8  4  4  6]]


In [12]:
arr

array([[ 2,  5, 18,  0],
       [ 5,  3, 18, 14],
       [ 8,  4,  4,  6]])

Galima naudoti ir tos pačios formos masyvą, sukuriamą pagal tam tikras sąlygas

In [10]:
arr > 5

array([[False, False,  True, False],
       [False, False,  True,  True],
       [ True, False, False,  True]])

Grąžinami elementai, tenkinantys tam tikrą sąlygą:

In [11]:
arr[arr > 5]

array([18, 18, 14,  8,  6])

Sąlygas taip pat galima logiškai apjungti:

In [13]:
(arr < 18) & (arr > 4)

array([[False,  True, False, False],
       [ True, False, False,  True],
       [ True, False, False,  True]])

In [14]:
arr[(arr < 18) & (arr > 4)]

array([ 5,  5, 14,  8,  6])