# Keep in mind reshape is dynamic

## Masyvo formos keitimas

In [4]:
import numpy as np
arr = np.random.randint(20, size=(3, 4))
arr

array([[15,  3, 18,  1],
       [16, 11, 13,  4],
       [ 8, 11,  4,  4]])

In [5]:
arr.shape

(3, 4)

Štai tvarka, pagal kurią yra saugomi masyvo nariai atmintyje:

In [7]:
arr.ravel()

array([15,  3, 18,  1, 16, 11, 13,  4,  8, 11,  4,  4])

Masyvas `arr` liko nepakitęs:

In [11]:
arr

array([[15,  3, 18,  1],
       [16, 11, 13,  4],
       [ 8, 11,  4,  4]])

`reshape` metodas perrikiuoja šiuos duomenis taip, kad eiliškumas ir kiekis nepasikeistų, bet būtų išlaikomi tam tikri ašių ilgiai

In [39]:
x = arr.reshape(3, 2, 2)
x

array([[[15,  3],
        [18,  1]],

       [[16, 11],
        [13,  4]],

       [[ 8, 11],
        [ 4,  4]]])

In [10]:
x.shape

(3, 2, 2)

Tačiau masyvas `x` saugomas toje pačioje vietoje, kaip ir `arr`:

In [50]:
print(f'x atminties adresas: {x.__array_interface__["data"][0]}, išskirta atminties vietos: {x.nbytes} bitai')
print(f'arr atminties adresas: {arr.__array_interface__["data"][0]}, išskirta atminties vietos: {x.nbytes} bitai')

x atminties adresas: 94108108557024, išskirta atminties vietos: 96 bitai
arr atminties adresas: 94108108557024, išskirta atminties vietos: 96 bitai


Vadinasi, pakeitus `x` reikšmes pasikeis ir `arr` reikšmės:

In [52]:
x[0, 0, 0] = -9999
x

array([[[-9999,     3],
        [   18,     1]],

       [[   16,    11],
        [   13,     4]],

       [[    8,    11],
        [    4,     4]]])

In [53]:
arr

array([[-9999,     3,    18,     1],
       [   16,    11,    13,     4],
       [    8,    11,     4,     4]])

Norint to išvengti galima `x` masyvą saugoti kitoje vietoje:

In [56]:
x = arr.reshape(3, 2, 2).copy()
print(f'x atminties adresas: {x.__array_interface__["data"][0]}, išskirta atminties vietos: {x.nbytes} bitai')

x atminties adresas: 94108108654512, išskirta atminties vietos: 96 bitai


Tada nereikės rūpintis dėl masyvo `arr`:

In [58]:
x[0, 0, 0] = 9999
x

array([[[9999,    3],
        [  18,    1]],

       [[  16,   11],
        [  13,    4]],

       [[   8,   11],
        [   4,    4]]])

In [59]:
arr

array([[-9999,     3,    18,     1],
       [   16,    11,    13,     4],
       [    8,    11,     4,     4]])

Iš kitos pusės, švaistoma atmintis. Todėl galima uždėti apsaugą nuo nepageidautinų keitimų:

In [64]:
arr.setflags(write = False)
x = arr.reshape(3, 2, 2)
x[0, 0, 0] = 9999

ValueError: assignment destination is read-only

## Masyvo plokštinimas
`np.ravel` ir `np.flatten` metodai paverčia masyvą plokščiu ir grąžina tą patį rezultatą. Tačiau `np.ravel()` nesukuria jo kopijos, o `np.flatten()` sukuria. 

In [74]:
arr.setflags(write = True)
y1, y2 = arr.ravel(), arr.flatten()
y1, y2

(array([100,   3,  18,   1,  16,  11,  13,   4,   8,  11,   4,   4]),
 array([100,   3,  18,   1,  16,  11,  13,   4,   8,  11,   4,   4]))

In [76]:
y1[0] = 100
y2[0] = 200
y1, y2

(array([100,   3,  18,   1,  16,  11,  13,   4,   8,  11,   4,   4]),
 array([200,   3,  18,   1,  16,  11,  13,   4,   8,  11,   4,   4]))

In [77]:
arr

array([[100,   3,  18,   1],
       [ 16,  11,  13,   4],
       [  8,  11,   4,   4]])

**Vadinasi**, `np.ravel()` veikia panašiai, kaip `np.reshape()`, tik yra labiau user-friendly.