# Basic indexing

In [18]:
import numpy as np
arr = np.random.randint(0, 20, size=(3, 4))

**Eilutės keitimas:**

In [5]:
arr[0] = np.arange(2, 6)
arr

array([[ 2,  3,  4,  5],
       [16, 17, 14, 14],
       [ 9, 16,  0,  0]])

**Bloko keitimas:**

In [6]:
arr[1:, 1:3] = -1
arr

array([[ 2,  3,  4,  5],
       [16, -1, -1, 14],
       [ 9, -1, -1,  0]])

### Indeksavimo rūšys

**Priėjimas prie elemento:**

In [7]:
arr[0,2], arr[0][2]

(4, 4)

**Indeksavimas pagal pirmą ašį**:

In [8]:
my_list = [0, 2]
print(arr[my_list])
print(arr[my_list, :])

[[ 2  3  4  5]
 [ 9 -1 -1  0]]
[[ 2  3  4  5]
 [ 9 -1 -1  0]]


**Indeksavimas pagal abi ašis**:

In [9]:
print(arr[[0, 2], ::2])

[[ 2  4]
 [ 9 -1]]


**Indeksavimas pagal antrą ašį**:

In [10]:
print(arr[:, ::2])

[[ 2  4]
 [16 -1]
 [ 9 -1]]


### Indeksų praleidimo slice'suose prasmė
Įsitikinsime, kad  `numpy` masyvų ir `list` indeksacija yra paremta `slice` tipo objektų naudojimu:

In [11]:
a = [7,8,9,4,5,6,1,2,3]
a[::2], a[None:None:2], a[slice(None,None,2)]

([7, 9, 5, 1, 3], [7, 9, 5, 1, 3], [7, 9, 5, 1, 3])

In [12]:
a[2:], a[2:None:None], a[slice(2, None, None)]

([9, 4, 5, 6, 1, 2, 3], [9, 4, 5, 6, 1, 2, 3], [9, 4, 5, 6, 1, 2, 3])

Taip pat panagrinėsime, kaip tokia indeksacija veikia `numpy` masyvuose, kai indeksuojamos abi ašys (`list` tipo objektai palaiko tik pirmos ašies indeksaciją):

In [13]:
arr

array([[ 2,  3,  4,  5],
       [16, -1, -1, 14],
       [ 9, -1, -1,  0]])

In [14]:
s1, s2 = slice(1,4,2), slice(1,3,2) # 1
l1, l2 = [1, 3], [1]

In [15]:
arr[s1, s2], arr[1:4:2, 1:3:2] #tokia pati indeksacija, paima tik pirmą eilutę ir pirmą stulpelį

(array([[-1]]), array([[-1]]))

In [16]:
arr[l1, s2], arr[[1, 3], 1:3:2] #tokia pati indeksacija, tačiau išmeta IndexError, nes neranda trečios eilutės

IndexError: index 3 is out of bounds for axis 0 with size 3

In [17]:
arr[s1, l2], arr[1:4:2, [1]] #tokia pati indeksacija, paima pirmą eilutę ir pirmą stulpelį

(array([[-1]]), array([[-1]]))