# Jumping between different ways of indexing

Jau susipažinome su Basic (vienmate), Boolean ir Advanced indeksacija. Dabar pažiūrėkime, kokie yra būdai pereiti iš vienos indeksacijos į kitą.

In [1]:
import numpy as np
arr = np.random.randint(20, size=(3, 4))
arr

array([[ 5, 15, 18, 19],
       [16,  3,  2, 12],
       [ 6,  1, 16, 12]])

**Boolean -> Advanced**

In [5]:
boolean_idx = arr < 10
boolean_idx

array([[ True, False, False, False],
       [False,  True,  True, False],
       [ True,  True, False, False]])

In [6]:
advanced_idx = np.where(boolean_idx)
advanced_idx

(array([0, 1, 1, 2, 2]), array([0, 1, 2, 0, 1]))

In [8]:
advanced_idx = np.nonzero(boolean_idx) #kitas būdas
advanced_idx

(array([0, 1, 1, 2, 2]), array([0, 1, 2, 0, 1]))

**Advanced -> Boolean**

In [32]:
boolean_idx = np.zeros_like(arr, dtype=bool)
boolean_idx[advanced_idx] = True
boolean_idx

array([[ True, False, False, False],
       [False,  True,  True, False],
       [ True,  True, False, False]])

## Interacting with flattened array.

Tiesioginis vaikščiojimas iš Basic (vienmatės) indeksacijos į daugiamatę yra dažnai negalimas. Norint tą padaryti vienmatę indeksaciją siūlau mėginti taikyti tik suplokštinto masyvo variantui.

In [15]:
shape, arr_ravel = arr.shape, arr.ravel()
shape, arr_ravel

((3, 4), array([ 5, 15, 18, 19, 16,  3,  2, 12,  6,  1, 16, 12]))

**Boolean -> Basic (of flattened array)**

In [17]:
basic_idx = np.flatnonzero(boolean_idx)

Įsitikinsime, kad tiek pradinio masyvo indeksacija, tiek suplokštinto masyvo indeksacija duos tuos pačius rezultatus

In [19]:
arr_ravel[basic_idx], arr[boolean_idx] 

(array([5, 3, 2, 6, 1]), array([5, 3, 2, 6, 1]))

**Advanced -> Basic (of flattened array)**

Jeigu duota kiekvieno nario eilutė ir stulpelis, tai turėtų būti nesunku apskaičiuoti, kelintas tai yra narys lentelėje

In [25]:
row, col = advanced_idx
basic_idx = row * 4 + col
print('masyvo forma:')
print('* * * *\n* * * *\n* * * *\n')
print('eilučių indeksai:   ', row)
print('stulpelių indeksai: ', col)
print('galutiniai indeksai:', basic_idx)

masyvo forma:
* * * *
* * * *
* * * *

eilučių indeksai:    [0 1 1 2 2]
stulpelių indeksai:  [0 1 2 0 1]
galutiniai indeksai: [0 5 6 8 9]


Įsitikinsime, kad perėjimas iš vienos indeksacijos į kitą duos tuos pačius rezultatus

In [26]:
arr_ravel[basic_idx], arr[advanced_idx] 

(array([5, 3, 2, 6, 1]), array([5, 3, 2, 6, 1]))

**Basic (of flattened array) -> Advanced**

In [30]:
advanced_idx = basic_idx//4, basic_idx%4 # because shape[1] is 4
advanced_idx

(array([0, 1, 1, 2, 2]), array([0, 1, 2, 0, 1]))

Kitas būdas:

In [31]:
np.divmod(basic_idx, 4)

(array([0, 1, 1, 2, 2]), array([0, 1, 2, 0, 1]))

**Basic (of flattened array) -> Boolean**

Pirmas būdas - pirma rasti `advanced_idx`

In [34]:
boolean_idx = np.zeros(shape, dtype=bool)
advanced_idx = np.divmod(basic_idx, 4)
boolean_idx[advanced_idx] = True
boolean_idx

array([[ True, False, False, False],
       [False,  True,  True, False],
       [ True,  True, False, False]])

Antras būdas - pakeitimus atlikti ant suplokštintos naujai sukurto masyvo versijos

In [35]:
boolean_idx = np.zeros_like(arr, dtype=bool)
boolean_idx.ravel()[basic_idx] = True
boolean_idx

array([[ True, False, False, False],
       [False,  True,  True, False],
       [ True,  True, False, False]])