# What is metadata of array?

In [13]:
import numpy as np
arr = np.random.randint(10, size=(4, 3), dtype=np.uint16)
arr

array([[0, 0, 7],
       [4, 7, 0],
       [9, 9, 4],
       [4, 1, 8]], dtype=uint16)

Tuple of array dimensions

In [14]:
arr.shape

(4, 3)

Number of elements in the array

In [15]:
arr.size

12

Data-type of the array’s elements

In [16]:
arr.dtype

dtype('uint16')

Length of one array element in bytes

In [17]:
arr.itemsize

2

Total bytes consumed by the elements of the array

In [18]:
arr.nbytes

24

Machine limits for integer type `np.uint8`

In [76]:
np.iinfo(np.uint8)

iinfo(min=0, max=255, dtype=uint8)

A role of machine limits

In [144]:
x1 = np.array([255,254,253], dtype=np.uint8)
x2 = x1 + 2
print(x1)
print(x2)

[255 254 253]
[  1   0 255]


And this is what happens with bits. There's simply no space to keep numbers larger than 255!

In [152]:
print(np.unpackbits(x1).reshape(-1, 8))

[[1 1 1 1 1 1 1 1]
 [1 1 1 1 1 1 1 0]
 [1 1 1 1 1 1 0 1]]


In [153]:
print(np.unpackbits(x2).reshape(-1, 8))

[[0 0 0 0 0 0 0 1]
 [0 0 0 0 0 0 0 0]
 [1 1 1 1 1 1 1 1]]
